server:
  host: 127.0.0.1
  port: 7777
redis:
  url: 127.0.0.1
  password: 123456
  port: 6379
datasource:
  host: 127.0.0.1
  databasename: xiaozao
  username: root
  password: "123456"
  port: 3306
  logPath: "/mnt/data/logs/xiaozao/beegoweb/sql"
logconfig:
  Filename: "/mnt/data/logs/xiaozao/beegoweb/test.log" # //string   //保存的文件名
  Maxlines: 1000000  #int//每个文件保存的最大行数，默认值 1000000
  #Maxsize #int      #//每个文件保存的最大尺寸，默认值是 1 << 28, //256 MB
  #Daily: true    #bool     #//是否按照每天 logrotate，默认是 true
  Maxdays: 14  #int     # //文件最多保存多少天，默认保存 7 天
  #Rotate: true   #bool    # //是否开启 logrotate，默认是 true
  #Level: 7    #string   #//日志保存的时候的级别，默认是 Trace 级别
  #Perm    # string   #//日志文件权限
  Separate: ["error", "warning", "info", "debug"] #[]string #//"emergency", "alert", "critical", "error", "warning", "notice", "info", "debug"